CREATE TABLE bugs (
	ccm_id BIGINT PRIMARY KEY,
	priority INTEGER DEFAULT 0,
	name VARCHAR(255) NOT NULL,
	url VARCHAR(255) NOT NULL,
	reported_by ENUM('UNKNOWN', 'INTERNAL', 'CUSTOMER') NOT NULL,
	creator_id BIGINT NOT NULL,
	task_status ENUM(
			'UNKNOWN', 'PROD_PRIORITIZATION', 'BENCHMARKING_IDEATION', 'PRODUCT', 'QA_PRE_ANALYSIS',
			'DEV_READY_FOR_DEVELOPMENT', 'DEV_PRESENTATION', 'PENDING_DEV_CORRECTION', 'IN_DEVELOPMENT', 'DEV_PAUSED',
            'BLOCKED_IN_QA', 'QA_HML_VERIFICATION', 'APPROVED_HOMOLOG', 'DEV_PRE_PROD_DEPLOY', 'QA_PRE_PROD_EVALUATION',
            'PRODUCT_PRE_PROD_EVALUATION', 'DEV_DEPLOY', 'POST_DEPLOY_VALIDATION', 'ROADMAP_QUEUE', 'DONE',
            'PENDING_PRODUCT_UX', 'PAUSED', 'FINISHED', 'STAKEHOLDERS_APPROVAL', 'DEVOPS', 'PRODUCT_HML_VERIFICATION',
            'AUTOMATION', 'INTERNAL'
	) NOT NULL,
	qa_status ENUM(
			'DONE', 'TODO', 'IN_PROGRESS', 'BLOCKED', 'NOT_APPLICABLE', 'PAUSED', 'PENDING', 'BUG_FIX', 'UNKNOWN'
	) NOT NULL,
	backend_status ENUM(
			'DONE', 'TODO', 'IN_PROGRESS', 'BLOCKED', 'NOT_APPLICABLE', 'PAUSED', 'PENDING', 'BUG_FIX', 'UNKNOWN'
	) NOT NULL,
	frontend_status ENUM(
			'DONE', 'TODO', 'IN_PROGRESS', 'BLOCKED', 'NOT_APPLICABLE', 'PAUSED', 'PENDING', 'BUG_FIX', 'UNKNOWN'
	) NOT NULL,
	created_at DATETIME NOT NULL,
	last_edited_at DATETIME NOT NULL,

	CONSTRAINT fk_creator_id FOREIGN KEY (creator_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;